// <auto-generated>
// This code was generated by LingoEngine.Director C#.
// </auto-generated>
using LingoEngine.Core;
using LingoEngine.Movies;

public class MovieBuilder : ILingoMovieBuilder
{
    public async Task<ILingoMovie> BuildAsync(ILingoPlayer player)
    {
        await player.LoadAsync<InternalExtCast>();
        await player.LoadAsync<DataCast>();
        await player.LoadAsync<SoundsCast>();
        var movie = player.NewMovie(@"Aaark Noid");
        movie.Tempo = 30;
        await new ScoreBuilder().BuildAsync(movie);
        return movie;
    }
}
