// <auto-generated>
// This code was generated by LingoEngine.Director C#.
// </auto-generated>
using LingoEngine.Core;
using LingoEngine.Movies;

public class MovieBuilder : ILingoMovieBuilder
{
    public ILingoMovie Build(ILingoPlayer player)
    {
        player.CastLibs.LoadCastLibFromBuilder(new InternalExtCast());
        player.CastLibs.LoadCastLibFromBuilder(new DataCast());
        player.CastLibs.LoadCastLibFromBuilder(new SoundsCast());
        var movie = player.NewMovie(@"Aaark Noid");
        movie.Tempo = 30;
        new ScoreBuilder().Build(movie);
        return movie;
    }
}
