// <auto-generated>
// This code was generated by LingoEngine.Director C#.
// </auto-generated>
using LingoEngine.Core;
using LingoEngine.Movies;
using LingoEngine.Sprites;
using LingoEngine.Members;
using AbstUI.Primitives;

public class ScoreBuilder : ILingoScoreBuilder
{
    public void Build(ILingoMovie movie)
    {
    }
}
