// <auto-generated>
// This code was generated by LingoEngine.Director C#.
// </auto-generated>
using LingoEngine.Casts;
using LingoEngine.Core;
using LingoEngine.Members;
using LingoEngine.Bitmaps;
using LingoEngine.Sounds;
using LingoEngine.FilmLoops;
using LingoEngine.Texts;
using LingoEngine.Shapes;
using LingoEngine.Scripts;
using LingoEngine.ColorPalettes;
using LingoEngine.Transitions;
using AbstUI.Primitives;

public class SoundsCast : ILingoCastLibBuilder
{
    public void Build(ILingoCastLibsContainer castLibs)
    {
        var cast = castLibs.AddCast(@"Sounds", false);
        var member1 = (LingoMemberSound)cast.Add(LingoMemberType.Sound, 1, @"S_Click", @"Media\Sounds\click.mp3", new APoint(0f, 0f));
        var member2 = (LingoMemberSound)cast.Add(LingoMemberType.Sound, 2, @"S_BtnStart", @"Media\Sounds\btnstart.mp3", new APoint(0f, 0f));
        var member3 = (LingoMemberSound)cast.Add(LingoMemberType.Sound, 3, @"S_Gong", @"Media\Sounds\gong.mp3", new APoint(0f, 0f));
        var member4 = (LingoMemberSound)cast.Add(LingoMemberType.Sound, 4, @"S_DeleteRow", @"Media\Sounds\deleterow.mp3", new APoint(0f, 0f));
        var member5 = (LingoMemberSound)cast.Add(LingoMemberType.Sound, 5, @"S_GO", @"Media\Sounds\go.mp3", new APoint(0f, 0f));
        var member6 = (LingoMemberSound)cast.Add(LingoMemberType.Sound, 6, @"S_LevelUp", @"Media\Sounds\level_up.mp3", new APoint(0f, 0f));
        var member7 = (LingoMemberSound)cast.Add(LingoMemberType.Sound, 7, @"S_Shhh1", @"Media\Sounds\shhh1.mp3", new APoint(0f, 0f));
        var member8 = (LingoMemberSound)cast.Add(LingoMemberType.Sound, 8, @"S_Terminated", @"Media\Sounds\terminated.mp3", new APoint(0f, 0f));
        var member9 = (LingoMemberSound)cast.Add(LingoMemberType.Sound, 9, @"S_Died", @"Media\Sounds\die.mp3", new APoint(0f, 0f));
        var member10 = (LingoMemberSound)cast.Add(LingoMemberType.Sound, 10, @"S_Nature", @"Media\Sounds\nature.mp3", new APoint(0f, 0f));
        member10.Loop = true;
        var member11 = (LingoMemberSound)cast.Add(LingoMemberType.Sound, 11, @"S_BlockFall1", @"Media\Sounds\blockfall_1.mp3", new APoint(0f, 0f));
        var member12 = (LingoMemberSound)cast.Add(LingoMemberType.Sound, 12, @"S_BlockFall2", @"Media\Sounds\blockfall_2.mp3", new APoint(0f, 0f));
        var member13 = (LingoMemberSound)cast.Add(LingoMemberType.Sound, 13, @"S_BlockFall3", @"Media\Sounds\blockfall_3.mp3", new APoint(0f, 0f));
        var member14 = (LingoMemberSound)cast.Add(LingoMemberType.Sound, 14, @"S_BlockFall4", @"Media\Sounds\blockfall_4.mp3", new APoint(0f, 0f));
        var member15 = (LingoMemberSound)cast.Add(LingoMemberType.Sound, 15, @"S_BlockFall5", @"Media\Sounds\blockfall_5.mp3", new APoint(0f, 0f));
        var member16 = (LingoMemberSound)cast.Add(LingoMemberType.Sound, 16, @"S_RowsDeleted_2", @"Media\Sounds\rows_deleted_2.mp3", new APoint(0f, 0f));
        var member17 = (LingoMemberSound)cast.Add(LingoMemberType.Sound, 17, @"S_RowsDeleted_3", @"Media\Sounds\rows_deleted_3.mp3", new APoint(0f, 0f));
        var member18 = (LingoMemberSound)cast.Add(LingoMemberType.Sound, 18, @"S_RowsDeleted_4", @"Media\Sounds\rows_deleted_4.mp3", new APoint(0f, 0f));
    }
}
