// Copyright to EmmanuelTheCreator.com
// This file was written in 2005, yeah a lot has evolved since then :-)
// Converted from original Lingo code, tried to keep it as identical as possible.

// <auto-generated>
// This code was generated by BlingoEngine.Director C#.
// </auto-generated>
using BlingoEngine.Casts;
using BlingoEngine.Core;
using BlingoEngine.Members;
using BlingoEngine.Bitmaps;
using BlingoEngine.Sounds;
using BlingoEngine.FilmLoops;
using BlingoEngine.Texts;
using BlingoEngine.Shapes;
using BlingoEngine.Scripts;
using BlingoEngine.ColorPalettes;
using BlingoEngine.Transitions;
using AbstUI.Primitives;

public class DataCast : IBlingoCastLibBuilder
{
    public async Task BuildAsync(IBlingoCastLibsContainer castLibs)
    {
        var cast = castLibs.AddCast(@"Data", false);
        var member1 = (BlingoMemberText)cast.Add(BlingoMemberType.Text, 1, @"Parameters", @"Media\Data\1_Parameters.txt", new APoint(0f, 0f));
        member1.SetTextMD(@"Local 2 0
Num_of_Players    3
Paint_Horizontal  15 
Paint_Vertical    11
Net/Local/Editor NetGame
NmbrOfMatch  9
Area_Hor    52 19
Area_Ver    37 14
Area_Height 60  
pVisualLimmiter 10 (100=much may be animated) 
ChoosenMemberMap  Standard
AccesoiresCastLib 5
pMap_mover   0
[1, 5, 7, 11, 15]
RandomMaps 0
 0 0



line_19 UP  Down Left Right Act1 Act2
Player1 126 125  123   124  119 121  
Player2  15  3    2     5    12  1    
--Para.  Ver Hor Tim NrBo Flam spd 3
Player1   1   5   60  1    2    7   1
Player2   2   1   60  1    2    7   2
Player3   3   1   60  1    2    7   3
Player4   4   1   60  1    2    5   4
Player5   5   1   60  1    2    5   1
Player6   6   1   60  1    2    5   1
Player7   7   1   60  1    2    5   1
Player8   8   1   60  1    2    5   1   
Player9   9   1   60  1    2    5   1
Player10  10  1   60  1    2    5   1
Player11  1   5   60  1    2    5   1
Player12  2   5   60  1    2    5   1
Player13  3   5   60  1    2    5   1 
Player14  4   5   60  1    2    5   1
Player15  5   5   60  1    2    5   1
Player16  6   5   60  1    2    5   1

// scores for how much Players
NbrPlayers  Winner Kill Selfkill- 
2             2     2     1   
3             2     2     1
4             3     2     1
5             3     2     1
6             4     2     1
7             5     2     1
8             6     2     2
9             6     2     2
10            6     2     2
11            6     2     2
12            6     2     2
13            6     2     2
14            6     3     2
15            6     3     2
16            6     3     2

DONT FORGET TO CORRECT THE NUMBER OF PLAYERZS WHEN ADD A PLYER in the plyerchoose
");
        member1.Width = 557;
        member1.Height = 798;
        var member2 = (BlingoFilmLoopMember)cast.Add(BlingoMemberType.FilmLoop, 2, @"BirdAnim", @"Media\Data\2_BirdAnim.png", new APoint(25f, 24.444445f));
        member2.Loop = true;
        member2.Width = 50;
        member2.Height = 50;
        var member3 = (BlingoMember)cast.Add(BlingoMemberType.Picture, 3, @"Bg", @"Media\Data\3_Bg.png", new APoint(38f, 149f));
        member3.Width = 77;
        member3.Height = 298;
        var member4 = (BlingoMemberText)cast.Add(BlingoMemberType.Text, 4, @"Player1", @"Media\Data\4_Player1.txt", new APoint(0f, 0f));
        member4.Width = 10;
        member4.Height = 10;
        var member5 = (BlingoMemberText)cast.Add(BlingoMemberType.Text, 5, @"Player2", @"Media\Data\5_Player2.txt", new APoint(0f, 0f));
        member5.Width = 10;
        member5.Height = 10;
        var member6 = (BlingoMember)cast.Add(BlingoMemberType.Picture, 6, @"Empty", @"Media\Data\6_Empty.png", new APoint(0f, 0f));
        var member7 = (BlingoMember)cast.Add(BlingoMemberType.Picture, 7, @"Game", @"Media\Data\7_Game.png", new APoint(365f, 273f));
        member7.Width = 730;
        member7.Height = 547;
        var member8 = (BlingoMemberText)cast.Add(BlingoMemberType.Text, 9, @"", @"Media\Data\9.txt", new APoint(0f, 0f));
        member8.SetTextMD(@"{{PARA:0}}\fi0\sb100\sa100 \uc2 Â© ?? 2005 by Emmanuel The Creator");
        member8.Width = 238;
        member8.Height = 11;
        var member9 = (BlingoMemberText)cast.Add(BlingoMemberType.Text, 10, @"", @"Media\Data\10.txt", new APoint(0f, 0f));
        member9.SetTextMD(@"{{PARA:0}}*\sb100\sa100 V1.0*");
        member9.Width = 84;
        member9.Height = 13;
        var member10 = (BlingoMemberText)cast.Add(BlingoMemberType.Text, 11, @"T_InputText", @"Media\Data\11_T_InputText.txt", new APoint(0f, 0f));
        member10.SetTextMD(@"{{PARA:0}}Input text");
        member10.Width = 300;
        member10.Height = 24;
        var member11 = (BlingoMemberText)cast.Add(BlingoMemberType.Text, 12, @"T_PopupTitle", @"Media\Data\12_T_PopupTitle.txt", new APoint(0f, 0f));
        member11.SetTextMD(@"{{PARA:0}}My title popup");
        member11.Width = 300;
        member11.Height = 24;
        var member12 = (BlingoMember)cast.Add(BlingoMemberType.Picture, 16, @"Bg", @"Media\Data\16_Bg.png", new APoint(32f, 9f));
        member12.Width = 65;
        member12.Height = 19;
        var member13 = (BlingoMember)cast.Add(BlingoMemberType.Picture, 17, @"Destroy1", @"Media\Data\17_Destroy1.png", new APoint(9f, 9f));
        member13.Width = 19;
        member13.Height = 19;
        var member14 = (BlingoMember)cast.Add(BlingoMemberType.Picture, 18, @"Destroy2", @"Media\Data\18_Destroy2.png", new APoint(9f, 9f));
        member14.Width = 19;
        member14.Height = 19;
        var member15 = (BlingoMember)cast.Add(BlingoMemberType.Picture, 19, @"Destroy3", @"Media\Data\19_Destroy3.png", new APoint(9f, 9f));
        member15.Width = 19;
        member15.Height = 19;
        var member16 = (BlingoMember)cast.Add(BlingoMemberType.Picture, 20, @"Destroy4", @"Media\Data\20_Destroy4.png", new APoint(9f, 9f));
        member16.Width = 19;
        member16.Height = 19;
        var member17 = (BlingoMember)cast.Add(BlingoMemberType.Picture, 21, @"Destroy5", @"Media\Data\21_Destroy5.png", new APoint(9f, 9f));
        member17.Width = 18;
        member17.Height = 19;
        var member18 = (BlingoMember)cast.Add(BlingoMemberType.Picture, 22, @"Destroy6", @"Media\Data\22_Destroy6.png", new APoint(9f, 9f));
        member18.Width = 19;
        member18.Height = 19;
        var member19 = (BlingoMember)cast.Add(BlingoMemberType.Picture, 23, @"Destroy8", @"Media\Data\23_Destroy8.png", new APoint(9f, 9f));
        member19.Width = 19;
        member19.Height = 19;
        var member20 = (BlingoMember)cast.Add(BlingoMemberType.Picture, 24, @"Destroy9", @"Media\Data\24_Destroy9.png", new APoint(9f, 5f));
        member20.Width = 19;
        member20.Height = 11;
        var member21 = (BlingoMember)cast.Add(BlingoMemberType.Picture, 25, @"Destroy7", @"Media\Data\25_Destroy7.png", new APoint(9f, 9f));
        member21.Width = 19;
        member21.Height = 19;
        var member22 = (BlingoMember)cast.Add(BlingoMemberType.Picture, 26, @"Destroy7", @"Media\Data\26_Destroy7.png", new APoint(9f, 9f));
        member22.Width = 19;
        member22.Height = 19;
        var member23 = (BlingoMemberText)cast.Add(BlingoMemberType.Text, 27, @"T_Score", @"Media\Data\27_T_Score.txt", new APoint(0f, 0f));
        member23.SetTextMD(@"{{PARA:0}}**0**");
        member23.Width = 99;
        member23.Height = 30;
        var member24 = (BlingoMemberText)cast.Add(BlingoMemberType.Text, 28, @"T_data", @"Media\Data\28_T_data.txt", new APoint(0f, 0f));
        member24.SetTextMD(@"{{PARA:0}}Level 0");
        member24.Width = 191;
        member24.Height = 24;
        var member25 = (BlingoMemberText)cast.Add(BlingoMemberType.Text, 29, @"T_OverScreen", @"Media\Data\29_T_OverScreen.txt", new APoint(0f, 0f));
        member25.SetTextMD(@"{{PARA:0}}**Go!**");
        member25.Width = 446;
        member25.Height = 41;
        var member26 = (BlingoMemberText)cast.Add(BlingoMemberType.Text, 30, @"T_OverScreen2", @"Media\Data\30_T_OverScreen2.txt", new APoint(0f, 0f));
        member26.SetTextMD(@"{{PARA:0}}**Go!**");
        member26.Width = 446;
        member26.Height = 41;
        var member27 = (BlingoMemberText)cast.Add(BlingoMemberType.Text, 31, @"T_InternetScoresNames", @"Media\Data\31_T_InternetScoresNames.txt", new APoint(0f, 0f));
        member27.SetTextMD(@"{{PARA:0}}**nele
{{PARA:0}}nele
{{PARA:0}}Michael
{{PARA:0}}Michael
{{PARA:0}}nele
{{PARA:0}}nele
{{PARA:0}}Manu
{{PARA:0}}Michael
{{PARA:0}}Michael
{{PARA:0}}Laura
{{PARA:0}}**");
        member27.Width = 65;
        member27.Height = 140;
        var member28 = (BlingoMemberText)cast.Add(BlingoMemberType.Text, 33, @"T_NewGame", @"Media\Data\33_T_NewGame.txt", new APoint(0f, 0f));
        member28.SetTextMD(@"{{PARA:0}}**Start**");
        member28.Width = 48;
        member28.Height = 16;
        var member29 = (BlingoMemberText)cast.Add(BlingoMemberType.Text, 34, @"T_Menu", @"Media\Data\34_T_Menu.txt", new APoint(0f, 0f));
        member29.Width = 10;
        member29.Height = 10;
        var member30 = (BlingoMemberText)cast.Add(BlingoMemberType.Text, 35, @"T_Pause", @"Media\Data\35_T_Pause.txt", new APoint(0f, 0f));
        member30.SetTextMD(@"{{PARA:0}}**Pause**");
        member30.Width = 52;
        member30.Height = 21;
        var member31 = (BlingoMemberText)cast.Add(BlingoMemberType.Text, 36, @"T_Pause", @"Media\Data\36_T_Pause.txt", new APoint(0f, 0f));
        member31.SetTextMD(@"{{PARA:0}}**Pause...**");
        member31.Width = 132;
        member31.Height = 41;
        var member32 = (BlingoMemberText)cast.Add(BlingoMemberType.Text, 37, @"T_InternetScores", @"Media\Data\37_T_InternetScores.txt", new APoint(0f, 0f));
        member32.SetTextMD(@"{{PARA:0}}**1700
{{PARA:0}}1682
{{PARA:0}}1673
{{PARA:0}}1586
{{PARA:0}}1397
{{PARA:0}}1371
{{PARA:0}}1349
{{PARA:0}}1157
{{PARA:0}}1110
{{PARA:0}}867
{{PARA:0}}**");
        member32.Width = 37;
        member32.Height = 140;
        var member33 = (BlingoMemberText)cast.Add(BlingoMemberType.Text, 38, @"PlayerName", @"Media\Data\38_PlayerName.txt", new APoint(0f, 0f));
        member33.SetTextMD(@"{{PARA:0}}**Manu**");
        member33.Width = 100;
        member33.Height = 16;
        var member34 = (BlingoMemberText)cast.Add(BlingoMemberType.Text, 39, @"", @"Media\Data\39.txt", new APoint(0f, 0f));
        member34.SetTextMD(@"{{PARA:0}}**Highscores**");
        member34.Width = 101;
        member34.Height = 24;
        var member35 = (BlingoMemberText)cast.Add(BlingoMemberType.Text, 40, @"", @"Media\Data\40.txt", new APoint(0f, 0f));
        member35.SetTextMD(@"{{PARA:0}}***Personal***");
        member35.Width = 56;
        member35.Height = 16;
        var member36 = (BlingoMemberText)cast.Add(BlingoMemberType.Text, 41, @"", @"Media\Data\41.txt", new APoint(0f, 0f));
        member36.SetTextMD(@"{{PARA:0}}***All***");
        member36.Width = 16;
        member36.Height = 16;
        var member37 = (BlingoMemberText)cast.Add(BlingoMemberType.Text, 42, @"", @"Media\Data\42.txt", new APoint(0f, 0f));
        member37.Width = 10;
        member37.Height = 10;
        var member38 = (BlingoMember)cast.Add(BlingoMemberType.Picture, 43, @"B_more", @"Media\Data\43_B_more.png", new APoint(11f, 12f));
        member38.Width = 22;
        member38.Height = 24;
        var member39 = (BlingoMemberText)cast.Add(BlingoMemberType.Text, 44, @"T_StartLevel", @"Media\Data\44_T_StartLevel.txt", new APoint(0f, 0f));
        member39.SetTextMD(@"{{PARA:0}}0");
        member39.Width = 26;
        member39.Height = 16;
        var member40 = (BlingoMember)cast.Add(BlingoMemberType.Picture, 45, @"B_back", @"Media\Data\45_B_back.png", new APoint(11f, 11f));
        member40.Width = 22;
        member40.Height = 23;
        var member41 = (BlingoMemberText)cast.Add(BlingoMemberType.Text, 46, @"T_StartLines", @"Media\Data\46_T_StartLines.txt", new APoint(0f, 0f));
        member41.SetTextMD(@"{{PARA:0}}0");
        member41.Width = 26;
        member41.Height = 16;
        var member42 = (BlingoMemberText)cast.Add(BlingoMemberType.Text, 47, @"", @"Media\Data\47.txt", new APoint(0f, 0f));
        member42.SetTextMD(@"{{PARA:0}}***Start Lines***");
        member42.Width = 77;
        member42.Height = 16;
        var member43 = (BlingoMemberText)cast.Add(BlingoMemberType.Text, 48, @"", @"Media\Data\48.txt", new APoint(0f, 0f));
        member43.SetTextMD(@"{{PARA:0}}***Start Level***");
        member43.Width = 77;
        member43.Height = 16;
        var member44 = (BlingoMemberText)cast.Add(BlingoMemberType.Text, 49, @"T_InternetScoresNamesP", @"Media\Data\49_T_InternetScoresNamesP.txt", new APoint(0f, 0f));
        member44.Width = 69;
        member44.Height = 10;
        var member45 = (BlingoMemberText)cast.Add(BlingoMemberType.Text, 50, @"T_InternetScoresP", @"Media\Data\50_T_InternetScoresP.txt", new APoint(0f, 0f));
        member45.Width = 37;
        member45.Height = 10;
        var member46 = (BlingoMember)cast.Add(BlingoMemberType.Picture, 51, @"B_Play", @"Media\Data\51_B_Play.png", new APoint(23f, 22f));
        member46.Width = 47;
        member46.Height = 45;
        var member47 = (BlingoMember)cast.Add(BlingoMemberType.Picture, 52, @"B_back2", @"Media\Data\52_B_back2.png", new APoint(10f, 11f));
        member47.Width = 20;
        member47.Height = 23;
        var member48 = (BlingoMember)cast.Add(BlingoMemberType.Picture, 53, @"alert", @"Media\Data\53_alert.png", new APoint(209f, 61f));
        member48.Width = 418;
        member48.Height = 123;
        var member49 = (BlingoMember)cast.Add(BlingoMemberType.Picture, 54, @"pause", @"Media\Data\54_pause.png", new APoint(209f, 61f));
        member49.Width = 418;
        member49.Height = 123;
        var member50 = (BlingoMemberText)cast.Add(BlingoMemberType.Text, 56, @"", @"Media\Data\56.txt", new APoint(0f, 0f));
        member50.SetTextMD(@"{{PARA:0}}***Loading parameters...***");
        member50.Width = 473;
        member50.Height = 21;
        var member51 = (BlingoMember)cast.Add(BlingoMemberType.Picture, 58, @"Block1", @"Media\Data\58_Block1.png", new APoint(8f, 8f));
        member51.Width = 17;
        member51.Height = 17;
        var member52 = (BlingoMember)cast.Add(BlingoMemberType.Picture, 59, @"Block2", @"Media\Data\59_Block2.png", new APoint(8f, 8f));
        member52.Width = 17;
        member52.Height = 17;
        var member53 = (BlingoMember)cast.Add(BlingoMemberType.Picture, 60, @"Block3", @"Media\Data\60_Block3.png", new APoint(8f, 8f));
        member53.Width = 17;
        member53.Height = 17;
        var member54 = (BlingoMember)cast.Add(BlingoMemberType.Picture, 61, @"Block4", @"Media\Data\61_Block4.png", new APoint(8f, 8f));
        member54.Width = 17;
        member54.Height = 17;
        var member55 = (BlingoMember)cast.Add(BlingoMemberType.Picture, 62, @"Block5", @"Media\Data\62_Block5.png", new APoint(8f, 8f));
        member55.Width = 17;
        member55.Height = 17;
        var member56 = (BlingoMember)cast.Add(BlingoMemberType.Picture, 63, @"Block6", @"Media\Data\63_Block6.png", new APoint(8f, 8f));
        member56.Width = 17;
        member56.Height = 17;
        var member57 = (BlingoMember)cast.Add(BlingoMemberType.Picture, 64, @"Block7", @"Media\Data\64_Block7.png", new APoint(8f, 8f));
        member57.Width = 17;
        member57.Height = 17;
        var member58 = (BlingoMember)cast.Add(BlingoMemberType.Picture, 70, @"Block1_2", @"Media\Data\70_Block1_2.png", new APoint(9f, 9f));
        member58.Width = 19;
        member58.Height = 19;
        var member59 = (BlingoMember)cast.Add(BlingoMemberType.Picture, 71, @"Block2_2", @"Media\Data\71_Block2_2.png", new APoint(9f, 9f));
        member59.Width = 19;
        member59.Height = 19;
        var member60 = (BlingoMember)cast.Add(BlingoMemberType.Picture, 72, @"Block3_2", @"Media\Data\72_Block3_2.png", new APoint(9f, 9f));
        member60.Width = 19;
        member60.Height = 19;
        var member61 = (BlingoMember)cast.Add(BlingoMemberType.Picture, 73, @"Block4_2", @"Media\Data\73_Block4_2.png", new APoint(9f, 9f));
        member61.Width = 19;
        member61.Height = 19;
        var member62 = (BlingoMember)cast.Add(BlingoMemberType.Picture, 74, @"Block5_2", @"Media\Data\74_Block5_2.png", new APoint(9f, 9f));
        member62.Width = 19;
        member62.Height = 19;
        var member63 = (BlingoMember)cast.Add(BlingoMemberType.Picture, 75, @"Block6_2", @"Media\Data\75_Block6_2.png", new APoint(9f, 9f));
        member63.Width = 19;
        member63.Height = 19;
        var member64 = (BlingoMember)cast.Add(BlingoMemberType.Picture, 76, @"Block7_2", @"Media\Data\76_Block7_2.png", new APoint(9f, 9f));
        member64.Width = 19;
        member64.Height = 19;
        var member65 = (BlingoMember)cast.Add(BlingoMemberType.Picture, 80, @"mouse0000", @"Media\Data\80_mouse0000.png", new APoint(24f, 22f));
        member65.Width = 48;
        member65.Height = 45;
        var member66 = (BlingoMember)cast.Add(BlingoMemberType.Picture, 81, @"mouse0001", @"Media\Data\81_mouse0001.png", new APoint(24f, 22f));
        member66.Width = 48;
        member66.Height = 45;
        var member67 = (BlingoMember)cast.Add(BlingoMemberType.Picture, 82, @"mouse0002", @"Media\Data\82_mouse0002.png", new APoint(24f, 22f));
        member67.Width = 48;
        member67.Height = 45;
        var member68 = (BlingoMember)cast.Add(BlingoMemberType.Picture, 83, @"mouse0003", @"Media\Data\83_mouse0003.png", new APoint(24f, 22f));
        member68.Width = 48;
        member68.Height = 45;
        var member69 = (BlingoMember)cast.Add(BlingoMemberType.Picture, 84, @"mouse0004", @"Media\Data\84_mouse0004.png", new APoint(24f, 22f));
        member69.Width = 48;
        member69.Height = 45;
        var member70 = (BlingoMember)cast.Add(BlingoMemberType.Picture, 85, @"mouse0005", @"Media\Data\85_mouse0005.png", new APoint(24f, 22f));
        member70.Width = 48;
        member70.Height = 45;
        var member71 = (BlingoMember)cast.Add(BlingoMemberType.Picture, 89, @"TetriGrounds_s", @"Media\Data\89_TetriGrounds_s.png", new APoint(117f, 22f));
        member71.Width = 232;
        member71.Height = 42;
        var member72 = (BlingoMember)cast.Add(BlingoMemberType.Picture, 100, @"bell0039", @"Media\Data\100_bell0039.png", new APoint(35f, 21f));
        member72.Width = 70;
        member72.Height = 42;
        var member73 = (BlingoMember)cast.Add(BlingoMemberType.Picture, 101, @"bell0000", @"Media\Data\101_bell0000.png", new APoint(35f, 21f));
        member73.Width = 70;
        member73.Height = 42;
        var member74 = (BlingoMember)cast.Add(BlingoMemberType.Picture, 102, @"bell0001", @"Media\Data\102_bell0001.png", new APoint(35f, 21f));
        member74.Width = 70;
        member74.Height = 42;
        var member75 = (BlingoMember)cast.Add(BlingoMemberType.Picture, 103, @"bell0002", @"Media\Data\103_bell0002.png", new APoint(35f, 21f));
        member75.Width = 70;
        member75.Height = 42;
        var member76 = (BlingoMember)cast.Add(BlingoMemberType.Picture, 104, @"bell0003", @"Media\Data\104_bell0003.png", new APoint(35f, 21f));
        member76.Width = 70;
        member76.Height = 42;
        var member77 = (BlingoMember)cast.Add(BlingoMemberType.Picture, 105, @"bell0004", @"Media\Data\105_bell0004.png", new APoint(35f, 21f));
        member77.Width = 70;
        member77.Height = 42;
        var member78 = (BlingoMember)cast.Add(BlingoMemberType.Picture, 106, @"bell0005", @"Media\Data\106_bell0005.png", new APoint(35f, 21f));
        member78.Width = 70;
        member78.Height = 42;
        var member79 = (BlingoMember)cast.Add(BlingoMemberType.Picture, 107, @"bell0006", @"Media\Data\107_bell0006.png", new APoint(35f, 21f));
        member79.Width = 70;
        member79.Height = 42;
        var member80 = (BlingoMember)cast.Add(BlingoMemberType.Picture, 108, @"bell0007", @"Media\Data\108_bell0007.png", new APoint(35f, 21f));
        member80.Width = 70;
        member80.Height = 42;
        var member81 = (BlingoMember)cast.Add(BlingoMemberType.Picture, 109, @"bell0008", @"Media\Data\109_bell0008.png", new APoint(35f, 21f));
        member81.Width = 70;
        member81.Height = 42;
        var member82 = (BlingoMember)cast.Add(BlingoMemberType.Picture, 110, @"bell0009", @"Media\Data\110_bell0009.png", new APoint(35f, 21f));
        member82.Width = 70;
        member82.Height = 42;
        var member83 = (BlingoMember)cast.Add(BlingoMemberType.Picture, 111, @"bell0010", @"Media\Data\111_bell0010.png", new APoint(35f, 21f));
        member83.Width = 70;
        member83.Height = 42;
        var member84 = (BlingoMember)cast.Add(BlingoMemberType.Picture, 112, @"bell0011", @"Media\Data\112_bell0011.png", new APoint(35f, 21f));
        member84.Width = 70;
        member84.Height = 42;
        var member85 = (BlingoMember)cast.Add(BlingoMemberType.Picture, 113, @"bell0012", @"Media\Data\113_bell0012.png", new APoint(35f, 21f));
        member85.Width = 70;
        member85.Height = 42;
        var member86 = (BlingoMember)cast.Add(BlingoMemberType.Picture, 114, @"bell0013", @"Media\Data\114_bell0013.png", new APoint(35f, 21f));
        member86.Width = 70;
        member86.Height = 42;
        var member87 = (BlingoMember)cast.Add(BlingoMemberType.Picture, 115, @"bell0014", @"Media\Data\115_bell0014.png", new APoint(35f, 21f));
        member87.Width = 70;
        member87.Height = 42;
        var member88 = (BlingoMember)cast.Add(BlingoMemberType.Picture, 116, @"bell0015", @"Media\Data\116_bell0015.png", new APoint(35f, 21f));
        member88.Width = 70;
        member88.Height = 42;
        var member89 = (BlingoMember)cast.Add(BlingoMemberType.Picture, 117, @"bell0016", @"Media\Data\117_bell0016.png", new APoint(35f, 21f));
        member89.Width = 70;
        member89.Height = 42;
        var member90 = (BlingoMember)cast.Add(BlingoMemberType.Picture, 118, @"bell0017", @"Media\Data\118_bell0017.png", new APoint(35f, 21f));
        member90.Width = 70;
        member90.Height = 42;
        var member91 = (BlingoMember)cast.Add(BlingoMemberType.Picture, 119, @"bell0018", @"Media\Data\119_bell0018.png", new APoint(35f, 21f));
        member91.Width = 70;
        member91.Height = 42;
        var member92 = (BlingoMember)cast.Add(BlingoMemberType.Picture, 120, @"bell0019", @"Media\Data\120_bell0019.png", new APoint(35f, 21f));
        member92.Width = 70;
        member92.Height = 42;
        var member93 = (BlingoMember)cast.Add(BlingoMemberType.Picture, 121, @"bell0020", @"Media\Data\121_bell0020.png", new APoint(35f, 21f));
        member93.Width = 70;
        member93.Height = 42;
        var member94 = (BlingoMember)cast.Add(BlingoMemberType.Picture, 122, @"bell0021", @"Media\Data\122_bell0021.png", new APoint(35f, 21f));
        member94.Width = 70;
        member94.Height = 42;
        var member95 = (BlingoMember)cast.Add(BlingoMemberType.Picture, 123, @"bell0022", @"Media\Data\123_bell0022.png", new APoint(35f, 21f));
        member95.Width = 70;
        member95.Height = 42;
        var member96 = (BlingoMember)cast.Add(BlingoMemberType.Picture, 124, @"bell0023", @"Media\Data\124_bell0023.png", new APoint(35f, 21f));
        member96.Width = 70;
        member96.Height = 42;
        var member97 = (BlingoMember)cast.Add(BlingoMemberType.Picture, 125, @"bell0024", @"Media\Data\125_bell0024.png", new APoint(35f, 21f));
        member97.Width = 70;
        member97.Height = 42;
        var member98 = (BlingoMember)cast.Add(BlingoMemberType.Picture, 126, @"bell0025", @"Media\Data\126_bell0025.png", new APoint(35f, 21f));
        member98.Width = 70;
        member98.Height = 42;
        var member99 = (BlingoMember)cast.Add(BlingoMemberType.Picture, 127, @"bell0026", @"Media\Data\127_bell0026.png", new APoint(35f, 21f));
        member99.Width = 70;
        member99.Height = 42;
        var member100 = (BlingoMember)cast.Add(BlingoMemberType.Picture, 128, @"bell0027", @"Media\Data\128_bell0027.png", new APoint(35f, 21f));
        member100.Width = 70;
        member100.Height = 42;
        var member101 = (BlingoMember)cast.Add(BlingoMemberType.Picture, 129, @"bell0028", @"Media\Data\129_bell0028.png", new APoint(35f, 21f));
        member101.Width = 70;
        member101.Height = 42;
        var member102 = (BlingoMember)cast.Add(BlingoMemberType.Picture, 130, @"bell0029", @"Media\Data\130_bell0029.png", new APoint(35f, 21f));
        member102.Width = 70;
        member102.Height = 42;
        var member103 = (BlingoMember)cast.Add(BlingoMemberType.Picture, 131, @"bell0040", @"Media\Data\131_bell0040.png", new APoint(35f, 21f));
        member103.Width = 70;
        member103.Height = 42;
        var member104 = (BlingoMember)cast.Add(BlingoMemberType.Picture, 132, @"bell0030", @"Media\Data\132_bell0030.png", new APoint(35f, 21f));
        member104.Width = 70;
        member104.Height = 42;
        var member105 = (BlingoMember)cast.Add(BlingoMemberType.Picture, 133, @"bell0031", @"Media\Data\133_bell0031.png", new APoint(35f, 21f));
        member105.Width = 70;
        member105.Height = 42;
        var member106 = (BlingoMember)cast.Add(BlingoMemberType.Picture, 134, @"bell0032", @"Media\Data\134_bell0032.png", new APoint(35f, 21f));
        member106.Width = 70;
        member106.Height = 42;
        var member107 = (BlingoMember)cast.Add(BlingoMemberType.Picture, 135, @"bell0033", @"Media\Data\135_bell0033.png", new APoint(35f, 21f));
        member107.Width = 70;
        member107.Height = 42;
        var member108 = (BlingoMember)cast.Add(BlingoMemberType.Picture, 136, @"bell0034", @"Media\Data\136_bell0034.png", new APoint(35f, 21f));
        member108.Width = 70;
        member108.Height = 42;
        var member109 = (BlingoMember)cast.Add(BlingoMemberType.Picture, 137, @"bell0035", @"Media\Data\137_bell0035.png", new APoint(35f, 21f));
        member109.Width = 70;
        member109.Height = 42;
        var member110 = (BlingoMember)cast.Add(BlingoMemberType.Picture, 138, @"bell0036", @"Media\Data\138_bell0036.png", new APoint(35f, 21f));
        member110.Width = 70;
        member110.Height = 42;
        var member111 = (BlingoMember)cast.Add(BlingoMemberType.Picture, 139, @"bell0037", @"Media\Data\139_bell0037.png", new APoint(35f, 21f));
        member111.Width = 70;
        member111.Height = 42;
        var member112 = (BlingoMember)cast.Add(BlingoMemberType.Picture, 140, @"bell0038", @"Media\Data\140_bell0038.png", new APoint(35f, 21f));
        member112.Width = 70;
        member112.Height = 42;
        var member113 = (BlingoMember)cast.Add(BlingoMemberType.Picture, 141, @"bell0039", @"Media\Data\141_bell0039.png", new APoint(35f, 21f));
        member113.Width = 70;
        member113.Height = 42;
    }
}

