// Copyright to EmmanuelTheCreator.com
// This file was written in 2005, yeah a lot has evolved since then :-)
// Converted from original Lingo code, tried to keep it as identical as possible.

// <auto-generated>
// This code was generated by BlingoEngine.Director C#.
// </auto-generated>
using BlingoEngine.Casts;
using BlingoEngine.Core;
using BlingoEngine.Members;
using BlingoEngine.Bitmaps;
using BlingoEngine.Sounds;
using BlingoEngine.FilmLoops;
using BlingoEngine.Texts;
using BlingoEngine.Shapes;
using BlingoEngine.Scripts;
using BlingoEngine.ColorPalettes;
using BlingoEngine.Transitions;
using AbstUI.Primitives;

public class InternalExtCast : IBlingoCastLibBuilder
{
    public async Task BuildAsync(IBlingoCastLibsContainer castLibs)
    {
        var cast = castLibs.AddCast(@"InternalExt", false);
        var member1 = (BlingoMemberScript)cast.Add(BlingoMemberType.Script, 1, @"Game stop", @"Media\InternalExt\1_Game stop.cs", new APoint(0f, 0f));
        var member2 = (BlingoMemberScript)cast.Add(BlingoMemberType.Script, 2, @"Bg Script", @"Media\InternalExt\2_Bg Script.cs", new APoint(0f, 0f));
        var member3 = (BlingoMemberScript)cast.Add(BlingoMemberType.Script, 3, @"SpriteManager", @"Media\InternalExt\3_SpriteManager.cs", new APoint(0f, 0f));
        var member4 = (BlingoMemberScript)cast.Add(BlingoMemberType.Script, 4, @"StarMovie", @"Media\InternalExt\4_StarMovie.cs", new APoint(0f, 0f));
        var member5 = (BlingoMemberScript)cast.Add(BlingoMemberType.Script, 5, @"ScoreManager", @"Media\InternalExt\5_ScoreManager.cs", new APoint(0f, 0f));
        var member6 = (BlingoMemberScript)cast.Add(BlingoMemberType.Script, 6, @"OverScreenText", @"Media\InternalExt\6_OverScreenText.cs", new APoint(0f, 0f));
        var member7 = (BlingoMemberScript)cast.Add(BlingoMemberType.Script, 7, @"Gfx", @"Media\InternalExt\7_Gfx.cs", new APoint(0f, 0f));
        var member8 = (BlingoMemberScript)cast.Add(BlingoMemberType.Script, 8, @"PlayerBlock", @"Media\InternalExt\8_PlayerBlock.cs", new APoint(0f, 0f));
        var member9 = (BlingoMemberScript)cast.Add(BlingoMemberType.Script, 9, @"Blocks", @"Media\InternalExt\9_Blocks.cs", new APoint(0f, 0f));
        var member10 = (BlingoMemberScript)cast.Add(BlingoMemberType.Script, 10, @"Block", @"Media\InternalExt\10_Block.cs", new APoint(0f, 0f));
        var member11 = (BlingoMemberScript)cast.Add(BlingoMemberType.Script, 11, @"Stop Menu", @"Media\InternalExt\11_Stop Menu.cs", new APoint(0f, 0f));
        var member12 = (BlingoMemberScript)cast.Add(BlingoMemberType.Script, 12, @"B_FontRollOver", @"Media\InternalExt\12_B_FontRollOver.cs", new APoint(0f, 0f));
        var member13 = (BlingoMemberScript)cast.Add(BlingoMemberType.Script, 13, @"B_NewGame", @"Media\InternalExt\13_B_NewGame.cs", new APoint(0f, 0f));
        var member14 = (BlingoMemberScript)cast.Add(BlingoMemberType.Script, 14, @"start", @"Media\InternalExt\14_start.cs", new APoint(0f, 0f));
        var member15 = (BlingoMemberScript)cast.Add(BlingoMemberType.Script, 15, @"AnimationScript", @"Media\InternalExt\15_AnimationScript.cs", new APoint(0f, 0f));
        var member16 = (BlingoMemberScript)cast.Add(BlingoMemberType.Script, 16, @"AppliBg", @"Media\InternalExt\16_AppliBg.cs", new APoint(0f, 0f));
        var member17 = (BlingoMemberScript)cast.Add(BlingoMemberType.Script, 17, @"score_get", @"Media\InternalExt\17_score_get.cs", new APoint(0f, 0f));
        var member18 = (BlingoMemberScript)cast.Add(BlingoMemberType.Script, 18, @"score_save", @"Media\InternalExt\18_score_save.cs", new APoint(0f, 0f));
        var member19 = (BlingoMemberScript)cast.Add(BlingoMemberType.Script, 19, @"ClassSubscibe", @"Media\InternalExt\19_ClassSubscibe.cs", new APoint(0f, 0f));
        var member20 = (BlingoMemberScript)cast.Add(BlingoMemberType.Script, 20, @"StartData_get", @"Media\InternalExt\20_StartData_get.cs", new APoint(0f, 0f));
        var member21 = (BlingoMemberScript)cast.Add(BlingoMemberType.Script, 21, @"temp", @"Media\InternalExt\21_temp.cs", new APoint(0f, 0f));
        var member22 = (BlingoMemberScript)cast.Add(BlingoMemberType.Script, 22, @"B_Execute", @"Media\InternalExt\22_B_Execute.cs", new APoint(0f, 0f));
        var member23 = (BlingoMemberScript)cast.Add(BlingoMemberType.Script, 23, @"TextCounter", @"Media\InternalExt\23_TextCounter.cs", new APoint(0f, 0f));
        var member24 = (BlingoMemberText)cast.Add(BlingoMemberType.Text, 24, @"", @"Media\InternalExt\24.txt", new APoint(0f, 0f));
        member24.SetTextMD(@"{{PARA:0}}***Loading parameters...***");
        member24.Width = 176;
        member24.Height = 21;
        var member25 = (BlingoMemberText)cast.Add(BlingoMemberType.Text, 25, @"", @"Media\InternalExt\25.txt", new APoint(0f, 0f));
        member25.SetTextMD(@"{{PARA:0}}***Please login first...***");
        member25.Width = 148;
        member25.Height = 21;
        var member26 = (BlingoMemberScript)cast.Add(BlingoMemberType.Script, 26, @"StartData_save", @"Media\InternalExt\26_StartData_save.cs", new APoint(0f, 0f));
        var member27 = (BlingoMemberScript)cast.Add(BlingoMemberType.Script, 28, @"MousePointer", @"Media\InternalExt\28_MousePointer.cs", new APoint(0f, 0f));
    }
}

