// Copyright to EmmanuelTheCreator.com
// This file was written in 2005, yeah a lot has evolved since then :-)
// Converted from original Lingo code, tried to keep it as identical as possible.

// <auto-generated>
// This code was generated by BlingoEngine.Director C#.
// </auto-generated>
using BlingoEngine.Core;
using BlingoEngine.Movies;

public class MovieBuilder : IBlingoMovieBuilder
{
    public async Task<IBlingoMovie> BuildAsync(IBlingoPlayer player)
    {
        await player.LoadAsync<InternalExtCast>();
        await player.LoadAsync<DataCast>();
        await player.LoadAsync<SoundsCast>();
        var movie = player.NewMovie(@"Aaark Noid");
        movie.Tempo = 30;
        await new ScoreBuilder().BuildAsync(movie);
        return movie;
    }
}

