// Copyright to EmmanuelTheCreator.com
// This file was written in 2005, yeah a lot has evolved since then :-)
// Converted from original Lingo code, tried to keep it as identical as possible.

// <auto-generated>
// This code was generated by BlingoEngine.Director C#.
// </auto-generated>
using BlingoEngine.Core;
using BlingoEngine.Movies;
using BlingoEngine.Sprites;
using BlingoEngine.Members;
using AbstUI.Primitives;

public class ScoreBuilder : IBlingoScoreBuilder
{
    public async Task BuildAsync(IBlingoMovie movie)
    {
        movie.AddSprite(4, 54, 64, 336f, 241f, s =>
        {
            s.Name = @"Sprite_4"; s.Visibility = true; s.ForeColor = new AColor(0, 0, 0, 0); s.BackColor = new AColor(255, 255, 255, 0); s.Member = movie.CastLib.GetMember(7, 1);
        });
        movie.AddSprite(5, 56, 64, 591f, 36f, s =>
        {
            s.Name = @"Sprite_5"; s.Visibility = true; s.ForeColor = new AColor(0, 0, 0, 0); s.BackColor = new AColor(255, 255, 255, 0); s.Member = movie.CastLib.GetMember(89, 2);
        });
        movie.AddSprite(6, 59, 64, 503f, 438f, s =>
        {
            s.Name = @"Sprite_6"; s.Visibility = true; s.ForeColor = new AColor(0, 0, 0, 0); s.BackColor = new AColor(255, 255, 255, 0); s.Member = movie.CastLib.GetMember(9, 1);
        });
        movie.AddSprite(7, 60, 64, 441f, 92f, s =>
        {
            s.Name = @"Sprite_7"; s.Visibility = true; s.ForeColor = new AColor(0, 0, 0, 0); s.BackColor = new AColor(255, 255, 255, 0); s.Member = movie.CastLib.GetMember(28, 1);
        });
        movie.AddSprite(9, 60, 64, 519f, 343f, s =>
        {
            s.Name = @"Sprite_9"; s.Visibility = true; s.ForeColor = new AColor(0, 0, 0, 0); s.BackColor = new AColor(255, 255, 255, 0); s.Member = movie.CastLib.GetMember(51, 2);
        });
        movie.AddSprite(11, 60, 64, 497f, 334f, s =>
        {
            s.Name = @"Sprite_11"; s.Visibility = true; s.ForeColor = new AColor(0, 0, 0, 0); s.BackColor = new AColor(255, 255, 255, 0); s.Member = movie.CastLib.GetMember(33, 2);
        });
        movie.AddSprite(12, 60, 64, 486f, 148f, s =>
        {
            s.Name = @"Sprite_12"; s.Visibility = true; s.ForeColor = new AColor(0, 0, 0, 0); s.BackColor = new AColor(255, 255, 255, 0); s.Member = movie.CastLib.GetMember(27, 2);
        });
        movie.AddSprite(14, 54, 64, 507f, 414f, s =>
        {
            s.Name = @"Sprite_14"; s.Visibility = true; s.ForeColor = new AColor(0, 0, 0, 0); s.BackColor = new AColor(255, 255, 255, 0); s.Member = movie.CastLib.GetMember(47, 2);
        });
        movie.AddSprite(15, 54, 64, 619f, 386f, s =>
        {
            s.Name = @"Sprite_15"; s.Visibility = true; s.ForeColor = new AColor(0, 0, 0, 0); s.BackColor = new AColor(255, 255, 255, 0); s.Member = movie.CastLib.GetMember(45, 2);
        });
        movie.AddSprite(16, 54, 64, 663f, 387f, s =>
        {
            s.Name = @"Sprite_16"; s.Visibility = true; s.ForeColor = new AColor(0, 0, 0, 0); s.BackColor = new AColor(255, 255, 255, 0); s.Member = movie.CastLib.GetMember(43, 2);
        });
        movie.AddSprite(17, 54, 64, 629f, 381f, s =>
        {
            s.Name = @"Sprite_17"; s.Visibility = true; s.ForeColor = new AColor(0, 0, 0, 0); s.BackColor = new AColor(255, 255, 255, 0); s.Member = movie.CastLib.GetMember(44, 2);
        });
        movie.AddSprite(18, 54, 64, 507f, 379f, s =>
        {
            s.Name = @"Sprite_18"; s.Visibility = true; s.ForeColor = new AColor(0, 0, 0, 0); s.BackColor = new AColor(255, 255, 255, 0); s.Member = movie.CastLib.GetMember(48, 2);
        });
        movie.AddSprite(19, 54, 64, 620f, 422f, s =>
        {
            s.Name = @"Sprite_19"; s.Visibility = true; s.ForeColor = new AColor(0, 0, 0, 0); s.BackColor = new AColor(255, 255, 255, 0); s.Member = movie.CastLib.GetMember(52, 2);
        });
        movie.AddSprite(20, 54, 64, 663f, 423f, s =>
        {
            s.Name = @"Sprite_20"; s.Visibility = true; s.ForeColor = new AColor(0, 0, 0, 0); s.BackColor = new AColor(255, 255, 255, 0); s.Member = movie.CastLib.GetMember(43, 2);
        });
        movie.AddSprite(21, 54, 64, 629f, 419f, s =>
        {
            s.Name = @"Sprite_21"; s.Visibility = true; s.ForeColor = new AColor(0, 0, 0, 0); s.BackColor = new AColor(255, 255, 255, 0); s.Member = movie.CastLib.GetMember(46, 2);
        });
        movie.AddSprite(22, 55, 64, 463f, 62f, s =>
        {
            s.Name = @"Sprite_22"; s.Visibility = true; s.ForeColor = new AColor(0, 0, 0, 0); s.BackColor = new AColor(255, 255, 255, 0); s.Member = movie.CastLib.GetMember(100, 2);
        });
        movie.AddSprite(24, 59, 64, 94f, 129f, s =>
        {
            s.Name = @"Sprite_24"; s.Visibility = true; s.ForeColor = new AColor(0, 0, 0, 0); s.BackColor = new AColor(255, 255, 255, 0); s.Member = movie.CastLib.GetMember(31, 2);
        });
        movie.AddSprite(25, 59, 64, 159f, 132f, s =>
        {
            s.Name = @"Sprite_25"; s.Visibility = true; s.ForeColor = new AColor(0, 0, 0, 0); s.BackColor = new AColor(255, 255, 255, 0); s.Member = movie.CastLib.GetMember(37, 2);
        });
        movie.AddSprite(26, 59, 64, 91f, 50f, s =>
        {
            s.Name = @"Sprite_26"; s.Visibility = true; s.ForeColor = new AColor(0, 0, 0, 0); s.BackColor = new AColor(255, 255, 255, 0); s.Member = movie.CastLib.GetMember(39, 2);
        });
        movie.AddSprite(27, 59, 64, 91f, 50f, s =>
        {
            s.Name = @"Sprite_27"; s.Visibility = true; s.ForeColor = new AColor(0, 0, 0, 0); s.BackColor = new AColor(255, 255, 255, 0); s.Member = movie.CastLib.GetMember(39, 2);
        });
        movie.AddSprite(28, 59, 64, 94f, 113f, s =>
        {
            s.Name = @"Sprite_28"; s.Visibility = true; s.ForeColor = new AColor(0, 0, 0, 0); s.BackColor = new AColor(255, 255, 255, 0); s.Member = movie.CastLib.GetMember(41, 2);
        });
        movie.AddSprite(29, 59, 64, 95f, 313f, s =>
        {
            s.Name = @"Sprite_29"; s.Visibility = true; s.ForeColor = new AColor(0, 0, 0, 0); s.BackColor = new AColor(255, 255, 255, 0); s.Member = movie.CastLib.GetMember(49, 2);
        });
        movie.AddSprite(30, 59, 64, 151f, 313f, s =>
        {
            s.Name = @"Sprite_30"; s.Visibility = true; s.ForeColor = new AColor(0, 0, 0, 0); s.BackColor = new AColor(255, 255, 255, 0); s.Member = movie.CastLib.GetMember(50, 2);
        });
        movie.AddSprite(35, 59, 64, 363f, 238f, s =>
        {
            s.Name = @"Sprite_35"; s.ForeColor = new AColor(0, 0, 0, 0); s.BackColor = new AColor(255, 255, 255, 0); s.Member = movie.CastLib.GetMember(54, 2);
        });
        movie.AddSprite(3, 2, 53, 600f, 60f, s =>
        {
            s.Name = @"Sprite_3"; s.Visibility = true; s.ForeColor = new AColor(0, 0, 0, 0); s.BackColor = new AColor(255, 255, 255, 0); s.Member = movie.CastLib.GetMember(89, 2);
        });
        movie.AddSprite(2, 19, 53, 132f, 268f, s =>
        {
            s.Name = @"Sprite_2"; s.Visibility = true; s.ForeColor = new AColor(0, 0, 0, 0); s.BackColor = new AColor(255, 255, 255, 0); s.Member = movie.CastLib.GetMember(56, 2);
        });
        movie.AddSprite(6, 2, 31, 751f, 394f, s =>
        {
            s.Name = @"Sprite_6"; s.Visibility = true; s.ForeColor = new AColor(0, 0, 0, 0); s.BackColor = new AColor(255, 255, 255, 0); s.Member = movie.CastLib.GetMember(2, 1);
        });
        movie.AddSprite(36, 59, 64, 363f, 238f, s =>
        {
            s.Name = @"Sprite_36"; s.Visibility = true; s.LocZ = 500; s.ForeColor = new AColor(0, 0, 0, 0); s.BackColor = new AColor(255, 255, 255, 0); s.Member = movie.CastLib.GetMember(53, 2);
        });
        movie.AddSprite(37, 59, 64, 200f, 200f, s =>
        {
            s.Name = @"Sprite_37"; s.Visibility = true; s.LocZ = 502; s.ForeColor = new AColor(0, 0, 0, 0); s.BackColor = new AColor(255, 255, 255, 0); s.Member = movie.CastLib.GetMember(12, 1);
        });
        movie.AddSprite(38, 59, 64, 200f, 230f, s =>
        {
            s.Name = @"Sprite_38"; s.Visibility = true; s.LocZ = 502; s.ForeColor = new AColor(0, 0, 0, 0); s.BackColor = new AColor(255, 255, 255, 0); s.Member = movie.CastLib.GetMember(11, 1);
        });
    }
}

