// Copyright to EmmanuelTheCreator.com
// This file was written in 2005, yeah a lot has evolved since then :-)
// Converted from original Lingo code, tried to keep it as identical as possible.

// <auto-generated>
// This code was generated by BlingoEngine.Director C#.
// </auto-generated>
using BlingoEngine.Casts;
using BlingoEngine.Core;
using BlingoEngine.Members;
using BlingoEngine.Bitmaps;
using BlingoEngine.Sounds;
using BlingoEngine.FilmLoops;
using BlingoEngine.Texts;
using BlingoEngine.Shapes;
using BlingoEngine.Scripts;
using BlingoEngine.ColorPalettes;
using BlingoEngine.Transitions;
using AbstUI.Primitives;

public class SoundsCast : IBlingoCastLibBuilder
{
    public async Task BuildAsync(IBlingoCastLibsContainer castLibs)
    {
        var cast = castLibs.AddCast(@"Sounds", false);
        var member1 = (BlingoMemberSound)cast.Add(BlingoMemberType.Sound, 1, @"S_Click", @"Media\Sounds\click.mp3", new APoint(0f, 0f));
        var member2 = (BlingoMemberSound)cast.Add(BlingoMemberType.Sound, 2, @"S_BtnStart", @"Media\Sounds\btnstart.mp3", new APoint(0f, 0f));
        var member3 = (BlingoMemberSound)cast.Add(BlingoMemberType.Sound, 3, @"S_Gong", @"Media\Sounds\gong.mp3", new APoint(0f, 0f));
        var member4 = (BlingoMemberSound)cast.Add(BlingoMemberType.Sound, 4, @"S_DeleteRow", @"Media\Sounds\deleterow.mp3", new APoint(0f, 0f));
        var member5 = (BlingoMemberSound)cast.Add(BlingoMemberType.Sound, 5, @"S_GO", @"Media\Sounds\go.mp3", new APoint(0f, 0f));
        var member6 = (BlingoMemberSound)cast.Add(BlingoMemberType.Sound, 6, @"S_LevelUp", @"Media\Sounds\level_up.mp3", new APoint(0f, 0f));
        var member7 = (BlingoMemberSound)cast.Add(BlingoMemberType.Sound, 7, @"S_Shhh1", @"Media\Sounds\shhh1.mp3", new APoint(0f, 0f));
        var member8 = (BlingoMemberSound)cast.Add(BlingoMemberType.Sound, 8, @"S_Terminated", @"Media\Sounds\terminated.mp3", new APoint(0f, 0f));
        var member9 = (BlingoMemberSound)cast.Add(BlingoMemberType.Sound, 9, @"S_Died", @"Media\Sounds\die.mp3", new APoint(0f, 0f));
        var member10 = (BlingoMemberSound)cast.Add(BlingoMemberType.Sound, 10, @"S_Nature", @"Media\Sounds\nature.mp3", new APoint(0f, 0f));
        member10.Loop = true;
        var member11 = (BlingoMemberSound)cast.Add(BlingoMemberType.Sound, 11, @"S_BlockFall1", @"Media\Sounds\blockfall_1.mp3", new APoint(0f, 0f));
        var member12 = (BlingoMemberSound)cast.Add(BlingoMemberType.Sound, 12, @"S_BlockFall2", @"Media\Sounds\blockfall_2.mp3", new APoint(0f, 0f));
        var member13 = (BlingoMemberSound)cast.Add(BlingoMemberType.Sound, 13, @"S_BlockFall3", @"Media\Sounds\blockfall_3.mp3", new APoint(0f, 0f));
        var member14 = (BlingoMemberSound)cast.Add(BlingoMemberType.Sound, 14, @"S_BlockFall4", @"Media\Sounds\blockfall_4.mp3", new APoint(0f, 0f));
        var member15 = (BlingoMemberSound)cast.Add(BlingoMemberType.Sound, 15, @"S_BlockFall5", @"Media\Sounds\blockfall_5.mp3", new APoint(0f, 0f));
        var member16 = (BlingoMemberSound)cast.Add(BlingoMemberType.Sound, 16, @"S_RowsDeleted_2", @"Media\Sounds\rows_deleted_2.mp3", new APoint(0f, 0f));
        var member17 = (BlingoMemberSound)cast.Add(BlingoMemberType.Sound, 17, @"S_RowsDeleted_3", @"Media\Sounds\rows_deleted_3.mp3", new APoint(0f, 0f));
        var member18 = (BlingoMemberSound)cast.Add(BlingoMemberType.Sound, 18, @"S_RowsDeleted_4", @"Media\Sounds\rows_deleted_4.mp3", new APoint(0f, 0f));
    }
}

